import { NextRequest } from "next/server";
import { db, auth } from "@/firebase/admin";
import { getRandomInterviewCover } from "@/lib/utils";
import { logger } from "@/lib/services/logger";

const AUTHORIZED_USER_ID = "i0bZW01fAeMaiqm2WSOKxFxwTAx2";

export async function POST(request: NextRequest) {
  try {
    // Verify authentication
    const authHeader = request.headers.get("authorization");
    let userId: string | null = null;

    if (authHeader?.startsWith("Bearer ")) {
      const idToken = authHeader.substring(7);
      try {
        const decodedClaims = await auth.verifyIdToken(idToken);
        userId = decodedClaims.uid;
      } catch (error) {
        logger.error("API Save Interview", "ID token verification failed", error);
      }
    }

    // Get request body
    const { 
      type, 
      role, 
      level, 
      techstack, 
      amount, 
      userid, 
      targetColleges, 
      targetBranches, 
      targetYears,
      questions // This will be generated by the client
    } = await request.json();

    // Use userid from request body if no auth header
    const finalUserId = userId || userid;

    // Verify authorization
    if (finalUserId !== AUTHORIZED_USER_ID) {
      logger.warn("API Save Interview", "Unauthorized access attempt", { userId: finalUserId });
      return Response.json(
        { success: false, error: "Unauthorized access" }, 
        { status: 403 }
      );
    }

    // Validate input
    if (!type || !role || !level || !techstack || !amount || !questions) {
      return Response.json(
        { success: false, error: "Missing required fields" }, 
        { status: 400 }
      );
    }

    // Validate targeting fields
    if (!targetColleges || !targetBranches || !targetYears) {
      return Response.json(
        { success: false, error: "Missing targeting fields (colleges, branches, years)" }, 
        { status: 400 }
      );
    }

    // Validate questions array
    if (!Array.isArray(questions) || questions.length === 0) {
      return Response.json(
        { success: false, error: "Questions must be a non-empty array" }, 
        { status: 400 }
      );
    }

    logger.info("API Save Interview", "Saving interview to database", {
      role,
      level,
      type,
      techstack,
      amount,
      questionsGenerated: questions.length,
      targetColleges: targetColleges.length,
      targetBranches: targetBranches.length,
      targetYears: targetYears.length,
      userId: finalUserId,
    });

    // Create interview object
    const createdAt = new Date().toISOString();
    const interview = {
      role: role,
      type: type,
      level: level,
      techstack: typeof techstack === 'string' 
        ? techstack.split(",").map((tech: string) => tech.trim())
        : Array.isArray(techstack) 
        ? techstack 
        : [],
      questions: questions,
      userId: finalUserId,
      finalized: true,
      coverImage: getRandomInterviewCover(`${finalUserId}-${createdAt}`),
      createdAt: createdAt,
      // Add targeting fields
      targetColleges: targetColleges,
      targetBranches: targetBranches,
      targetYears: targetYears,
    };

    // Save to database
    const docRef = await db.collection("interviews").add(interview);

    logger.info("API Save Interview", "Interview saved successfully", {
      interviewId: docRef.id,
      questionsGenerated: questions.length,
      targetColleges: targetColleges.length,
      targetBranches: targetBranches.length,
      targetYears: targetYears.length,
      userId: finalUserId,
    });

    return Response.json({ 
      success: true, 
      interviewId: docRef.id,
      questionsGenerated: questions.length 
    }, { status: 200 });

  } catch (error) {
    logger.error("API Save Interview", "Interview save failed", error);
    console.error("Error:", error);
    return Response.json(
      { 
        success: false, 
        error: error instanceof Error ? error.message : "Unknown error occurred" 
      }, 
      { status: 500 }
    );
  }
}

export async function GET() {
  return Response.json({ 
    success: true, 
    message: "Save Interview API",
    status: "active" 
  }, { status: 200 });
}